theme: minima
title: 
author: Vikash Kumar
email: kumarvikas134@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is a test for github website

# social links
twitter_username: blaberingmonk # DO NOT include the @ character, or else the build will fail!
github_username:  vikasFid # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

